[app]
name = "beadj-backend"

[[services]]
name = "api"
type = "web"

[services.build]
type = "buildpack"

[services.ports]
port = 8000
protocol = "http"

[services.env]
PORT = "8000"
# Add your environment variables in Koyeb dashboard:
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET  
# SPOTIFY_PLAYLIST_ID
# SPOTIFY_REDIRECT_URI
# SUPABASE_URL
# SUPABASE_ANON_KEY
# ADMIN_PASSWORD
# SPOTIFY_AUTH_PASSWORD

[services.health_checks]
http = { path = "/health", port = 8000 }

[services.scaling]
min = 1
max = 1
